<?php

namespace App\Modifiers;

use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Statamic\Modifiers\Modifier;
use Statamic\Statamic;

class Toc extends Modifier
{
    private $context;

    /**
     * Modify a value
     *
     * @param  mixed  $value  The value to be modified
     * @param  array  $params  Any parameters used in the modifier
     * @param  array  $context  Contextual values
     * @return mixed
     */
    public function index($value, $params, $context)
    {
        $this->context = $context;

        $creatingIds = Arr::get($params, 0) == 'ids';

        // Here maxHeadingLevels is set to either 5 (when creating IDs) or 3 (for TOC)
        [$toc, $content] = $this->create($value, $creatingIds ? 5 : 3);

        return $creatingIds ? $content : $toc;
    }

    // Good golly this thing is ugly.
    private function create($content, $maxHeadingLevels)
    {
        // First try with h2-hN headings
        preg_match_all('/<h([2-'.$maxHeadingLevels.'])([^>]*)>(.*)<\/h[2-'.$maxHeadingLevels.']>/i', $content, $matches, PREG_SET_ORDER);

        // If we don't have enough entries, include h1 headings as well
        if (count($matches) < 3) {
            preg_match_all('/<h([1-'.$maxHeadingLevels.'])([^>]*)>(.*)<\/h[1-'.$maxHeadingLevels.']>/i', $content, $matches, PREG_SET_ORDER);
        }

        if (! $matches) {
            return [null, $content];
        }

        // Track unique anchor IDs across the document
        global $anchors;
        $anchors = [];

        // Initialize TOC with an unordered list
        $toc = '<ul class="o-scroll-spy-timeline__toc js__scroll-spy-toc">'."\n";
        $i = 0;
        $tiCounter = 1; // Add counter for --ti values

        foreach ($matches as $heading) {
            // Track the starting heading level for proper list nesting
            if ($i == 0) {
                $startlvl = ($heading[1] == '1') ? '2' : $heading[1];
            }

            // Normalize h1 to same level as h2
            $lvl = ($heading[1] == '1') ? '2' : $heading[1];

            // Get the ID attribute generated by Commonmark
            $anchor = Str::of($heading[0])->after('id="')->before('"');

            // Extract title from title attribute or use heading text
            $ret = preg_match('/title=[\'|"](.*)?[\'|"]/i', stripslashes($heading[2]), $title);

            if ($ret && $title[1] != '') {
                $title = stripslashes($title[1]);
            } else {
                $title = $heading[3];
            }

            $title = trim(strip_tags($title));

            // Handle nested list structure based on heading levels
            if ($i > 0) {
                if ($prevlvl < $lvl) {
                    // Start a new nested list wrapped in li, don't increment counter for parent li
                    $toc .= "\n".'<li><ul>'."\n";
                } elseif ($prevlvl > $lvl) {
                    // Close current item and any nested lists
                    $toc .= '</li>'."\n";
                    while ($prevlvl > $lvl) {
                        $toc .= '</ul></li>'."\n".'</li>'."\n";
                        $prevlvl--;
                    }
                } else {
                    // Close current item at same level
                    $toc .= '</li>'."\n";
                }
            }

            // Add TOC entry with --ti style (only for leaf nodes)
            $toc .= '<li style="--ti: --'.$tiCounter.'"><a href="#'.$anchor.'">'.$title.'</a>';
            $tiCounter++;

            $prevlvl = $lvl;

            $i++;
        }

        unset($anchors);

        while ($lvl > $startlvl) {
            $toc .= "\n</ul>";
            $lvl--;
        }

        $toc .= '</li>'."\n";
        $toc .= '</ul>'."\n";

        return [$toc, $content];
    }

    /**
     * Safely extracts value from Statamic Value objects
     */
    private function valueGet($value)
    {
        if ($value instanceof \Statamic\Fields\Value) {
            return $value->value();
        }

        return $value;
    }

    private function slugify($text)
    {
        $slugified = Statamic::modify($text)->replace('&amp;', '')->slugify()->stripTags();
        // Remove 'code-code' from the slugified text e.g. Otherwise "the `@` ignore symbol" gets converted to `the-code-code-ignore-symbol`
        $slugified = str_replace('code-code-', '', $slugified);
        // Remove HTML entity remnants that might be left after processing
        // Only remove these if they appear as standalone words or at word boundaries
        $slugified = preg_replace('/\b(codelt|rt|gtcode)\b/', '', $slugified);

        return $slugified;
    }
}
